import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { TopBar } from "./components/topbar";
import { Footer } from "./components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TopBar/>
        {children}
        {
          // Lembre-se de dar atenção as funções de cada arquivo no projeto, e que cada script de
          // aplicação visual em React, precisa ser passado para o html (renderizado), e como o Toast
          // foi anunciado em auth-form.tsx, precisamos renderizá-lo em alguma introdução <html>!
        }
        <Toaster/>
        <Footer/>
      </body>
    </html>
  );
}
